name: Sottie
favicon: null
layout_spectrum: 0.9532102670054883
typography_spectrum: 0.22935656807385385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#270345'
    - '#40344a'
    - '#486100'
    - '#9b7b00'
    - '#95c800'
  brandStrength: 1
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
