name: Sottie
favicon: null
layout_spectrum: 0.74598
typography_spectrum: 0.56519
title: Sottie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#270345'
    - '#40344a'
    - '#486100'
    - '#9b7b00'
    - '#95c800'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
